source 'https://rubygems.org'

gemspec path: '../'

# https://github.com/rails/rails/pull/14519
# gem 'rails', github: 'tute/rails', ref: '34585e2795fce950d9d9cb1cf97b43cc9b5a5f15'
gem 'rails', path: '../../rails-dev-box/rails'

gem 'timecop'
